version: '3.6'

services:

  redis:
    image: 'redis:alpine'
    command: redis-server --protected-mode no #--requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  dash_app:
    container_name: finance_dashapp
    restart: always
    build: ./backend
    volumes:
      - ./3rdparty:/src/3rdparty:ro
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: gunicorn -w 1 -b :8000 app:server

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - dash_app

  
volumes:
  redis:

