version: '3.6'

services:

  redis:
    image: 'redis:alpine'
    command: redis-server --protected-mode no #--requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  dash_app:
    container_name: finance_dashapp
    restart: always
    build: ./backend
    volumes:
      - ./3rdparty:/src/3rdparty:ro
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongodb
    command: gunicorn -w 1 -b :8000 app:server

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - dash_app

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
    ports:
      - 27017:27017
  
  rabbitmq:
    #image: rabbitmq
    build: ./rabbitmq
    ports:
      - 15672:15672
    #command: rabbitmq-server
    #expose:
    #  - 5672
    #  - 15672
    #healthcheck:
    #  test: [ "CMD", "nc", "-z", "localhost", "5672" ]
    #  interval: 5s
    #  timeout: 15s
    #  retries: 1

volumes:
  redis:
  db-data:
  mongo-config:
